apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pharos.fullname" . }}-config
  labels:
    {{- include "pharos.labels" . | nindent 4 }}
data:
  config.toml: |
{{ include "pharos.configToml" . | indent 4 }}
