{{- if .Values.ui.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pharos.fullname" . }}-ui
  labels:
    {{- include "pharos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pharos.ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pharos.ui.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: jellyfin-web
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8097
              protocol: TCP
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pharos.fullname" . }}-ui
  labels:
    {{- include "pharos.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "pharos.ui.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ui.port }}
      targetPort: http
      protocol: TCP
{{- end }}
